#!/usr/bin/env python3
"""hero_image.py, branded hero images for blog posts.

Matches the house style used on the blog index: large cream serif title on the
left, a gold supporting line beneath it, the brand mark at the bottom, and a
gold line-art illustration on the right with a few decorative marks.

Programmatic rather than generated by an image model. The result is
deterministic, on brand every time, costs nothing, and cannot invent garbled
text or a wrong logo. It doubles as the OG image, so it is raster rather than
SVG: social platforms will not render SVG.

Needs rsvg-convert and cwebp, both small.
"""

import pathlib, re, subprocess, tempfile

# The palette lives in brand.yaml under art_direction, so the video renderer
# and anything added later share it. These literals remain as a fallback: a
# missing config key must not stop an image being made.
INK, GOLD, CREAM = "#1a2730", "#947f5b", "#f0ece4"


def palette(brand=None):
    """Brand colours, from config where present."""
    a = ((brand or {}).get("art_direction") or {}).get("palette") or {}
    return (a.get("ink", INK), a.get("gold", GOLD), a.get("cream", CREAM))
W, H = 1200, 630
SERIF = "DejaVu Serif, Georgia, 'Times New Roman', serif"
SANS = "DejaVu Sans, Poppins, Arial, sans-serif"

# Line-art illustrations, drawn in a 400x400 box. Chosen deterministically from
# the slug so an article always keeps the same image.
ART = {
    "lighthouse": ("a lighthouse above water", """
        <path d="M200 60 L168 250 L232 250 Z" />
        <path d="M160 250 H240" /><path d="M172 205 H228" /><path d="M176 165 H224" />
        <path d="M200 60 V34" /><circle cx="200" cy="26" r="7" />
        <path d="M182 96 H218" /><path d="M178 130 H222" />
        <path d="M120 292 q22 -14 44 0 t44 0 t44 0 t44 0" />
        <path d="M108 322 q22 -14 44 0 t44 0 t44 0 t44 0" />
        <path d="M132 352 q22 -14 44 0 t44 0 t44 0" />"""),
    "anchor": ("an anchor with rope", """
        <circle cx="200" cy="62" r="20" />
        <path d="M200 82 V300" /><path d="M148 122 H252" />
        <path d="M104 214 q0 96 96 106 q96 -10 96 -106" />
        <path d="M104 214 l-24 22 M104 214 l26 20" />
        <path d="M296 214 l24 22 M296 214 l-26 20" />
        <path d="M200 300 l-16 -20 M200 300 l16 -20" />"""),
    "compass": ("a compass", """
        <circle cx="200" cy="190" r="128" /><circle cx="200" cy="190" r="96" />
        <path d="M132 258 L200 108 L268 258 L200 208 Z" />
        <path d="M200 44 V62 M200 318 V336 M46 190 H64 M336 190 H354" />
        <path d="M92 82 l14 14 M294 82 l-14 14 M92 298 l14 -14 M294 298 l-14 -14" />"""),
    "bridge": ("a suspension bridge", """
        <path d="M56 288 H344" /><path d="M104 288 V96" /><path d="M296 288 V96" />
        <path d="M104 96 C 160 26, 240 26, 296 96" />
        <path d="M136 288 V124 M168 288 V108 M200 288 V102 M232 288 V108 M264 288 V124" />
        <path d="M56 196 H104 M296 196 H344" />
        <path d="M56 320 q30 -14 60 0 t60 0 t60 0 t60 0" />"""),
    "scales": ("a set of balance scales", """
        <path d="M200 56 V292" /><path d="M138 292 H262" />
        <path d="M200 92 L84 140 M200 92 L316 140" />
        <path d="M28 140 H140 M260 140 H372" />
        <path d="M32 140 a52 52 0 0 0 104 0" /><path d="M264 140 a52 52 0 0 0 104 0" />
        <circle cx="200" cy="72" r="9" />"""),
    "steps": ("a flight of steps rising to the right", """
        <path d="M46 300 H116 V246 H186 V192 H256 V138 H326 V84 H396" />
        <path d="M46 300 V276 M116 246 V300 M186 192 V300 M256 138 V300 M326 84 V300" />
        <path d="M326 60 V38 M300 44 l18 14 M352 44 l-18 14" />"""),
}
ORDER = sorted(ART)

SPARKLE = ('<path d="M{x} {y} l0 -{s} M{x} {y} l0 {s} M{x} {y} l-{s} 0 M{x} {y} l{s} 0" '
           'stroke-width="2" opacity="0.7"/>')


def _esc(s):
    return str(s or "").replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def _wrap(text, per_line):
    words, lines, cur = str(text or "").split(), [], ""
    for w in words:
        if len(cur) + len(w) + 1 <= per_line:
            cur = f"{cur} {w}".strip()
        else:
            lines.append(cur); cur = w
    if cur:
        lines.append(cur)
    return lines


def build_svg(title, subtitle, slug):
    name = ORDER[sum(ord(c) for c in slug) % len(ORDER)]
    described, art = ART[name]

    # Fit the whole title. Step the size down until it fits in four lines
    # rather than truncating, because a chopped headline is worse than a
    # slightly smaller one, and titles vary a lot in length.
    for t_size, per_line in ((68, 20), (60, 23), (54, 26), (48, 29), (42, 33)):
        t_lines = _wrap(title, per_line)
        if len(t_lines) <= 4:
            break
    else:
        t_lines = _wrap(title, 33)[:4]
    y = {1: 190, 2: 150, 3: 132, 4: 118}.get(len(t_lines), 118)

    title_svg = "".join(
        f'<text x="72" y="{y + i * t_size * 1.14:.0f}" font-family="{SERIF}" '
        f'font-size="{t_size}" fill="{CREAM}">{_esc(l)}</text>'
        for i, l in enumerate(t_lines))

    sub_y = y + len(t_lines) * t_size * 1.14 + 26
    s_lines = _wrap(subtitle, 42)[:2]
    sub_svg = "".join(
        f'<text x="72" y="{sub_y + i * 38:.0f}" font-family="{SANS}" font-size="27" '
        f'font-weight="bold" fill="{GOLD}">{_esc(l)}</text>'
        for i, l in enumerate(s_lines))

    sparkles = "".join(
        SPARKLE.format(x=x, y=sy, s=s)
        for x, sy, s in ((78, 46, 13), (150, 96, 9), (330, 60, 11)))

    return f'''<svg xmlns="http://www.w3.org/2000/svg" width="{W}" height="{H}" viewBox="0 0 {W} {H}">
  <rect width="{W}" height="{H}" fill="{INK}"/>
  <g transform="translate(770,110) scale(0.92)" fill="none" stroke="{GOLD}"
     stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round" opacity="0.45">
    {art}
    {sparkles}
  </g>
  {title_svg}
  {sub_svg}
  <text x="72" y="{H - 54}" font-family="{SANS}" font-size="21" fill="{CREAM}"
        opacity="0.72">AI Readiness Partner</text>
</svg>''', f"{_esc(title)}. AI Readiness Partner. A faded gold line-art drawing of {described} sits to the right of the title."


def render(title, slug, out_path, subtitle=""):
    """Write a WebP hero image. Returns (path, alt_text)."""
    svg, alt = build_svg(title, subtitle, slug)
    out = pathlib.Path(out_path)
    out.parent.mkdir(parents=True, exist_ok=True)

    with tempfile.NamedTemporaryFile("w", suffix=".svg", delete=False) as f:
        f.write(svg); svg_path = f.name
    png_path = svg_path.replace(".svg", ".png")
    try:
        subprocess.run(["rsvg-convert", "-w", str(W), "-h", str(H), "-o", png_path, svg_path],
                       check=True, capture_output=True)
        subprocess.run(["cwebp", "-quiet", "-q", "88", png_path, "-o", str(out)],
                       check=True, capture_output=True)
    finally:
        for p in (svg_path, png_path):
            pathlib.Path(p).unlink(missing_ok=True)
    return out, alt


# ─── Social cards ──────────────────────────────────────────────────

# X renders 16:9 in timeline; LinkedIn prefers 1.91:1. One 1200x675 card serves
# both without cropping the text.
SOCIAL_W, SOCIAL_H = 1200, 675


def _key_line(text, limit=170):
    """The sentence worth putting on the card.

    Prefers the sharpest short sentence rather than the first, because the first
    line of a post is often setup and the payoff is the line that stops a
    scroll. Ignores the link and hashtag lines entirely.
    """
    cleaned = []
    for line in (text or "").splitlines():
        s = line.strip()
        if not s or s.startswith("#") or s.startswith("http"):
            continue
        cleaned.append(s)
    body = " ".join(cleaned)
    sentences = [s.strip() for s in re.split(r"(?<=[.?!])\s+", body) if s.strip()]
    if not sentences:
        return (body or "")[:limit]
    # A short punchy sentence beats a long one on a card, but a three word
    # fragment carries nothing, so require some substance.
    usable = [s for s in sentences if 30 <= len(s) <= limit]
    return (usable[0] if usable else sentences[0])[:limit]


def social_card(text, slug, out_path, kicker="AI READINESS PARTNER"):
    """A branded quote card for a social post. Returns (path, alt_text)."""
    line = _key_line(text)
    name = ORDER[sum(ord(c) for c in slug) % len(ORDER)]
    described, art = ART[name]

    for size, per_line in ((56, 23), (50, 26), (44, 30), (39, 34), (34, 39)):
        lines = _wrap(line, per_line)
        if len(lines) <= 5:
            break
    else:
        lines = _wrap(line, 45)[:5]

    top = SOCIAL_H // 2 - ((len(lines) - 1) * size * 1.16) / 2 - 6
    body_svg = "".join(
        f'<text x="70" y="{top + i * size * 1.16:.0f}" font-family="{SERIF}" '
        f'font-size="{size}" fill="{CREAM}">{_esc(l)}</text>'
        for i, l in enumerate(lines))

    svg = f'''<svg xmlns="http://www.w3.org/2000/svg" width="{SOCIAL_W}" height="{SOCIAL_H}" viewBox="0 0 {SOCIAL_W} {SOCIAL_H}">
  <rect width="{SOCIAL_W}" height="{SOCIAL_H}" fill="{INK}"/>
  <g transform="translate(900,170) scale(0.62)" fill="none" stroke="{GOLD}"
     stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round" opacity="0.30">
    {art}
  </g>
  <text x="70" y="76" font-family="{SANS}" font-size="17" letter-spacing="4"
        fill="{GOLD}">{_esc(kicker)}</text>
  <rect x="70" y="96" width="64" height="2" fill="{GOLD}"/>
  {body_svg}
  <text x="70" y="{SOCIAL_H - 52}" font-family="{SANS}" font-size="19"
        fill="{CREAM}" opacity="0.66">aireadinesspartner.com</text>
  <rect x="0" y="{SOCIAL_H-7}" width="{SOCIAL_W}" height="7" fill="{GOLD}" opacity="0.85"/>
</svg>'''

    out = pathlib.Path(out_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile("w", suffix=".svg", delete=False) as f:
        f.write(svg); svg_path = f.name
    png_path = svg_path.replace(".svg", ".png")
    try:
        subprocess.run(["rsvg-convert", "-w", str(SOCIAL_W), "-h", str(SOCIAL_H),
                        "-o", png_path, svg_path], check=True, capture_output=True)
        # X and LinkedIn both accept PNG, and PNG keeps text crisp where a lossy
        # format would soften it.
        pathlib.Path(png_path).replace(out)
    finally:
        pathlib.Path(svg_path).unlink(missing_ok=True)
    alt = (f"{line} AI Readiness Partner. A faded gold line-art drawing of "
           f"{described} sits to the right.")
    return out, alt[:420]
